name: Publish New VPKEdit Version
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Version'
        default: '1.2.3'
        required: true
        type: string

env:
  # https://github.com/craftablescience/VPKEdit/releases/download/TAG/VPKEdit-Linux-Installer-gcc-Release.zip
  DOWNLOAD_REPO_NAME: craftablescience/VPKEdit
  DOWNLOAD_FILENAME_LINUX: VPKEdit-Linux-Installer-gcc-Release.zip

jobs:
  vpkedit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Packages
        run: |
          sudo apt install -y apt-utils dpkg-dev gnupg

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ''

      - name: Download Release
        run: |
          curl -L "https://github.com/${{ env.DOWNLOAD_REPO_NAME }}/releases/download/v${{ inputs.VERSION }}/${{ env.DOWNLOAD_FILENAME_LINUX }}" -o __package__.zip
          7z x __package__.zip
          mv "VPKEdit-${{ inputs.VERSION }}-Linux.deb" "${{ github.workspace }}/debian/package-VPKEdit_${{ inputs.VERSION }}_amd64.deb"
          rm __package__.zip

      - name: Create Packages Metadata
        working-directory: '${{ github.workspace }}/debian'
        run: |
          # Packages & Packages.gz
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
      
          # Release & Release.gpg & InRelease
          apt-ftparchive release . > Release
          gpg --default-key "lauralewisdev@gmail.com" -abs -o - Release > Release.gpg
          gpg --default-key "lauralewisdev@gmail.com" --clearsign -o - Release > InRelease

      - name: Push Changes
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "vpkedit: v${{ inputs.VERSION }}"
          git push
